Repository OptimumDev/Natural-selected-cards, pull requests merged in 2020-05, with the labels that each got.

#7 Belianin api
  NaturalSelectedCards/ClientApp/natural-selected-cards/.gitignore
  NaturalSelectedCards/ClientApp/natural-selected-cards/README.md
  NaturalSelectedCards/ClientApp/natural-selected-cards/package-lock.json
  NaturalSelectedCards/ClientApp/natural-selected-cards/package.json
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/favicon.ico
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/index.html
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/logo192.png
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/logo512.png
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/manifest.json
  NaturalSelectedCards/ClientApp/natural-selected-cards/public/robots.txt
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/App.css
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/App.js
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/App.test.js
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/index.css
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/index.js
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/logo.svg
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/serviceWorker.js
  NaturalSelectedCards/ClientApp/natural-selected-cards/src/setupTests.js
  NaturalSelectedCards/Controllers/CardsController.cs
  NaturalSelectedCards/Controllers/DecksController.cs
  NaturalSelectedCards/Controllers/OidcConfigurationController.cs
  NaturalSelectedCards/Controllers/WeatherForecastController.cs
  NaturalSelectedCards/Data/ApplicationDbContext.cs
  NaturalSelectedCards/Data/Migrations/00000000000000_CreateIdentitySchema.Designer.cs
  NaturalSelectedCards/Data/Migrations/00000000000000_CreateIdentitySchema.cs
  NaturalSelectedCards/Data/Migrations/ApplicationDbContextModelSnapshot.cs
  NaturalSelectedCards/Models/ApplicationUser.cs
  NaturalSelectedCards/Models/Requests/CardRequest.cs
  NaturalSelectedCards/Models/Requests/CopyDeckRequest.cs
  NaturalSelectedCards/Models/Requests/CreateDeckRequest.cs
  NaturalSelectedCards/Models/Requests/UpdateDeckRequest.cs
  NaturalSelectedCards/Models/Responses/CardResponse.cs
  NaturalSelectedCards/Models/Responses/DeckResponse.cs
  NaturalSelectedCards/NaturalSelectedCards.csproj
  NaturalSelectedCards/Pages/Error.cshtml
  NaturalSelectedCards/Pages/Error.cshtml.cs
  NaturalSelectedCards/Pages/Shared/_LoginPartial.cshtml
  NaturalSelectedCards/Pages/_ViewImports.cshtml
  NaturalSelectedCards/Program.cs
  NaturalSelectedCards/Startup.cs
  NaturalSelectedCards/WeatherForecast.cs
  NaturalSelectedCards/app.db
  NaturalSelectedCards/wwwroot/index.html
Labels: api

#13 Data layer
  NaturalSelectedCards.sln
  NaturalSelectedCards/Data/Entities/CardEntity.cs
  NaturalSelectedCards/Data/Entities/DeckEntity.cs
  NaturalSelectedCards/Data/Repositories/ICardRepository.cs
  NaturalSelectedCards/Data/Repositories/IDeckRepository.cs
  NaturalSelectedCards/Data/Repositories/MongoCardRepository.cs
  NaturalSelectedCards/Data/Repositories/MongoDeckRepository.cs
  Tests/MongoCardRepositoryShould.cs
  Tests/MongoDeckRepositoryShould.cs
  Tests/Tests.csproj
Labels: database

#15 build react
  NaturalSelectedCards/wwwroot/asset-manifest.json
  NaturalSelectedCards/wwwroot/favicon.ico
  NaturalSelectedCards/wwwroot/index.html
  NaturalSelectedCards/wwwroot/logo192.png
  NaturalSelectedCards/wwwroot/logo512.png
  NaturalSelectedCards/wwwroot/manifest.json
  NaturalSelectedCards/wwwroot/precache-manifest.1af3788cdde3d137a465d5d48996e51e.js
  NaturalSelectedCards/wwwroot/robots.txt
  NaturalSelectedCards/wwwroot/service-worker.js
  NaturalSelectedCards/wwwroot/static/css/main.232b63dd.chunk.css
  NaturalSelectedCards/wwwroot/static/css/main.232b63dd.chunk.css.map
  NaturalSelectedCards/wwwroot/static/js/2.cf71f0c3.chunk.js
  NaturalSelectedCards/wwwroot/static/js/2.cf71f0c3.chunk.js.LICENSE.txt
  NaturalSelectedCards/wwwroot/static/js/2.cf71f0c3.chunk.js.map
  NaturalSelectedCards/wwwroot/static/js/main.a4c2f7fd.chunk.js
  NaturalSelectedCards/wwwroot/static/js/main.a4c2f7fd.chunk.js.map
  NaturalSelectedCards/wwwroot/static/js/runtime-main.c558bbda.js
  NaturalSelectedCards/wwwroot/static/js/runtime-main.c558bbda.js.map
  NaturalSelectedCards/wwwroot/static/media/Flat_cross_icon.01d4eced.svg
  NaturalSelectedCards/wwwroot/static/media/account_circle-white-48dp.f0b80d9b.svg
  NaturalSelectedCards/wwwroot/static/media/brightness_4-black-48dp.bf8278b3.svg
  NaturalSelectedCards/wwwroot/static/media/brightness_4-white-48dp.9e80471f.svg
Labels: frontend

#14 Logic
  NaturalSelectedCards/Logic/Managers/IDeckManager.cs
  NaturalSelectedCards/Logic/Models/CardModel.cs
  NaturalSelectedCards/Logic/Models/DeckModel.cs
Labels: logic

#19 Auth
  NaturalSelectedCards/Auth/GoogleAuthenticationHandler.cs
  NaturalSelectedCards/Auth/GoogleAuthenticationSchemeOptions.cs
  NaturalSelectedCards/Controllers/CardsController.cs
  NaturalSelectedCards/Controllers/DecksController.cs
  NaturalSelectedCards/Controllers/UserController.cs
  NaturalSelectedCards/Models/Responses/UserInfoResponse.cs
  NaturalSelectedCards/NaturalSelectedCards.csproj
  NaturalSelectedCards/Startup.cs
  NaturalSelectedCards/Utils/Constants/AuthenticationSchemes.cs
  NaturalSelectedCards/Utils/Constants/ClaimTypes/CustomClaimTypes.cs
  NaturalSelectedCards/Utils/Constants/ClaimTypes/GoogleClaimTypes.cs
  NaturalSelectedCards/Utils/Constants/CookieKeys.cs
  NaturalSelectedCards/Utils/Constants/Urls.cs
  NaturalSelectedCards/Utils/CookieHelper.cs
  NaturalSelectedCards/Utils/EnvironmentVariables.cs
  NaturalSelectedCards/Utils/Extensions/EnumerableExtensions.cs
  NaturalSelectedCards/Utils/Extensions/HttpResponseExtensions.cs
Labels: authorization

#22 Database hosting
  NaturalSelectedCards/Data/MongoDatabaseBuilder.cs
  NaturalSelectedCards/Models/Settings/DatabaseSettings.cs
  NaturalSelectedCards/Startup.cs
  NaturalSelectedCards/Utils/EnvironmentVariables.cs
  NaturalSelectedCards/appsettings.json
  Tests/MongoCardRepositoryShould.cs
  Tests/MongoDeckRepositoryShould.cs
Labels: database, hosting

#21 Frontend Auth
  NaturalSelectedCards/Startup.cs
  NaturalSelectedCards/Utils/Constants/Policies.cs
  NaturalSelectedCards/Utils/Constants/Urls.cs
  NaturalSelectedCards/Utils/EnvironmentVariables.cs
  natural-selected-cards/package-lock.json
  natural-selected-cards/package.json
  natural-selected-cards/public/favicon.ico
  natural-selected-cards/public/index.html
  natural-selected-cards/public/logo192.png
  natural-selected-cards/public/logo512.png
  natural-selected-cards/public/manifest.json
  natural-selected-cards/src/Components/App/App.css
  natural-selected-cards/src/Components/App/App.js
  natural-selected-cards/src/Components/AppHeader/AppHeader.css
  natural-selected-cards/src/Components/AppHeader/AppHeader.js
  natural-selected-cards/src/Components/AppName/AppName.css
  natural-selected-cards/src/Components/AppName/AppName.js
  natural-selected-cards/src/Components/CardCarousel/CardCarousel.css
  natural-selected-cards/src/Components/ChooseDialog/ChooseDialog.css
  natural-selected-cards/src/Components/Deck/Deck.css
  natural-selected-cards/src/Components/Deck/Deck.js
  natural-selected-cards/src/Components/DeckSubview/DeckSubview.css
  natural-selected-cards/src/Components/DeckSubview/DeckSubview.js
  natural-selected-cards/src/Components/IconButton/IconButton.css
  natural-selected-cards/src/Components/IconButton/IconButton.js
  natural-selected-cards/src/Components/Pages/DecksPage/DeckPage.css
  natural-selected-cards/src/Components/Pages/DecksPage/DecksPage.js
  natural-selected-cards/src/Components/Pages/GamePage/GamePage.css
  natural-selected-cards/src/Components/Pages/GamePage/GamePage.js
  natural-selected-cards/src/Components/Pages/MainPage/MainPage.css
  natural-selected-cards/src/Components/Pages/MainPage/MainPage.js
  natural-selected-cards/src/Components/Pages/Page/Page.css
  natural-selected-cards/src/Components/Pages/Page/Page.js
  natural-selected-cards/src/Components/Pages/ViewDeckPage/ViewDeckPage.css
  natural-selected-cards/src/Components/Pages/ViewDeckPage/ViewDeckPage.js
  natural-selected-cards/src/Components/User/User.js
  natural-selected-cards/src/Constants/ApiUrls.js
  natural-selected-cards/src/Constants/GoogleAuthorization.js
  natural-selected-cards/src/Constants/LocalStorageKeys.js
  natural-selected-cards/src/Constants/PageNames.js
  natural-selected-cards/src/Utils/fetchHelper.js
  natural-selected-cards/src/Utils/localStorageHelper.js
  natural-selected-cards/src/Utils/server.js
  natural-selected-cards/src/images/exit_to_app-black-48dp.svg
  natural-selected-cards/src/images/exit_to_app-white-48dp.svg
  natural-selected-cards/src/images/logo192x192-dark.png
  natural-selected-cards/src/images/logo192x192.png
Labels: authorization, frontend

#23 Logic
  NaturalSelectedCards/Logic/Managers/DeckManager.cs
  NaturalSelectedCards/Logic/Managers/IDeckManager.cs
  NaturalSelectedCards/Logic/Mappers/CardMapper.cs
  NaturalSelectedCards/Logic/Mappers/DeckMapper.cs
  azure-pipelines.yml
Labels: logic

#28 Users
  NaturalSelectedCards/Data/Entities/UserEntity.cs
  NaturalSelectedCards/Data/Repositories/IUserRepository.cs
  NaturalSelectedCards/Data/Repositories/MongoUserRepository.cs
  Tests/MongoUserRepositoryShould.cs
Labels: database

#29 Backend logic using
  NaturalSelectedCards/Auth/GoogleAuthenticationHandler.cs
  NaturalSelectedCards/Controllers/CardsController.cs
  NaturalSelectedCards/Controllers/DecksController.cs
  NaturalSelectedCards/Controllers/UserController.cs
  NaturalSelectedCards/Data/MongoDatabaseBuilder.cs
  NaturalSelectedCards/Models/Requests/CopyDeckRequest.cs
  NaturalSelectedCards/Models/Requests/CreateCardRequest.cs
  NaturalSelectedCards/Models/Requests/CreateDeckRequest.cs
  NaturalSelectedCards/Models/Requests/UpdateDeckRequest.cs
  NaturalSelectedCards/Startup.cs
  NaturalSelectedCards/Utils/Extensions/ControllerExtensions.cs
  NaturalSelectedCards/Utils/Extensions/DeckRepositoryExtensions.cs
Labels: api

#30 Logic
  NaturalSelectedCards/Logic/Managers/DeckManager.cs
Labels: logic

#33 Frontend api using
  NaturalSelectedCards/Data/Repositories/MongoUserRepository.cs
  NaturalSelectedCards/Logic/Managers/DeckManager.cs
  NaturalSelectedCards/Startup.cs
  natural-selected-cards/src/Components/App/App.js
  natural-selected-cards/src/Components/Deck/Deck.css
  natural-selected-cards/src/Components/DeckSubview/DeckSubview.js
  natural-selected-cards/src/Components/Pages/CreatePage/CreatePage.js
  natural-selected-cards/src/Components/Pages/DecksPage/DecksPage.js
  natural-selected-cards/src/Components/Pages/GamePage/GamePage.js
  natural-selected-cards/src/Components/Pages/MainPage/MainPage.js
  natural-selected-cards/src/Components/Pages/Page/Page.js
  natural-selected-cards/src/Components/Pages/ViewDeckPage/ViewDeckPage.js
  natural-selected-cards/src/Components/User/User.js
  natural-selected-cards/src/Constants/ApiUrls.js
  natural-selected-cards/src/Utils/fetchHelper.js
  natural-selected-cards/src/Utils/localStorageHelper.js
  natural-selected-cards/src/Utils/server.js
  natural-selected-cards/src/deckExamples.js
Labels: api, frontend

#38 Fix "No matching creator found" error
  NaturalSelectedCards/Data/Entities/CardEntity.cs
Labels: bug
